[project]
name = "fevisubathontimer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-socketio>=5.5.1",
    "obsws-python==1.8.0",
]
